name: Build
description: 빌드/CI 관련 변경 요청에 사용하세요.
title: "[BUILD]: "
labels:
  - BUILD
body:
  - type: input
    id: area
    attributes:
      label: 대상 영역
      description: 변경되는 빌드/CI 영역을 적어주세요.
      placeholder: "예: GitHub Actions, Docker, Gradle, npm"
    validations:
      required: true
  - type: textarea
    id: change-summary
    attributes:
      label: 변경 내용
      description: 어떤 변경을 하려는지 요약하세요.
      placeholder: "예: CI 캐시 추가로 빌드 시간 단축"
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: 변경 이유
      description: 왜 필요한지 간단히 설명하세요.
      placeholder: "예: 빌드 시간이 길어짐"
  - type: textarea
    id: impact
    attributes:
      label: 영향 및 테스트
      description: 영향 범위와 확인할 테스트를 적어주세요.
      placeholder: "예: GitHub Actions 워크플로 검증"
