name: Feature
description: 새로운 기능을 제안할 때 사용하세요.
title: "feat(<scope>): <subject>"
labels:
  - feat
body:
  - type: input
    id: scope
    attributes:
      label: Scope
      description: 변경되는 코드 영역(모듈, 패키지, 도메인 등)
      placeholder: "예: auth, profile, billing"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 기능 설명
      description: 제안하는 기능의 세부 내용 또는 해결하려는 문제를 간단히 작성하세요.
      placeholder: |
        - 문제점: 현재 SSO 미지원으로 기업 사용자 온보딩이 지연됩니다.
        - 제안: OAuth2 Device Flow 지원 추가
    validations:
      required: true
