name: 문의 / 지원 요청
description: 질문이나 지원 요청이 있을 때 사용하세요.
title: "[문의]: "
labels:
  - question
body:
  - type: input
    id: question-title
    attributes:
      label: 질문 제목
      description: 질문의 요약을 입력하세요.
      placeholder: "예: API 응답 오류 문의"
  - type: textarea
    id: details
    attributes:
      label: 상세 내용
      description: 질문 또는 지원 요청의 상세 내용을 작성하세요.
  - type: textarea
    id: expected-answer
    attributes:
      label: 기대하는 답변 형태
      description: 어떤 형태의 답변을 기대하는지 설명하세요.
